import {
  Clock,
  Users,
  Shield,
  Zap,
  BarChart3,
  CheckCircle2,
  TrendingUp,
  Building,
  Coffee,
  Bot,
  Mic,
  Globe,
  Star,
  Heart,
  Award,
  BookOpen,
  FileText,
  MessageSquare,
  PlayCircle,
  Image,
  Settings,
  ArrowRight,
  Sparkles,
  AlertCircle,
  Scale,
  ShieldCheck,
  Wine,
  Utensils,
  GlassWater,
  Handshake,
  Calculator,
  Radio,
  Search,
  Lightbulb,
  Target,
  Rocket,
  Puzzle,
  Layers,
  Layout,
  Monitor,
  Smartphone,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps icon name strings to Lucide icon components.
 * Used by block components that receive icon names from the CMS.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  clock: Clock,
  users: Users,
  shield: Shield,
  zap: Zap,
  "bar-chart": BarChart3,
  "bar-chart-3": BarChart3,
  "check-circle": CheckCircle2,
  "check-circle-2": CheckCircle2,
  "trending-up": TrendingUp,
  building: Building,
  coffee: Coffee,
  bot: Bot,
  mic: Mic,
  globe: Globe,
  star: Star,
  heart: Heart,
  award: Award,
  "book-open": BookOpen,
  "file-text": FileText,
  "message-square": MessageSquare,
  "play-circle": PlayCircle,
  image: Image,
  settings: Settings,
  "arrow-right": ArrowRight,
  sparkles: Sparkles,
  "alert-circle": AlertCircle,
  scale: Scale,
  "shield-check": ShieldCheck,
  wine: Wine,
  utensils: Utensils,
  "glass-water": GlassWater,
  handshake: Handshake,
  calculator: Calculator,
  radio: Radio,
  search: Search,
  lightbulb: Lightbulb,
  target: Target,
  rocket: Rocket,
  puzzle: Puzzle,
  layers: Layers,
  layout: Layout,
  monitor: Monitor,
  smartphone: Smartphone,
};

/**
 * Resolves an icon name string to a Lucide icon component.
 * Falls back to Sparkles if the name is not found.
 */
export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Sparkles;
}
