import * as fs from "fs";
import * as path from "path";
import type { JourneyIR } from "@smartout/journey-ir";
import type { ProtocolTestOutput } from "../protocols/types";

/**
 * Generates a UX audit report from a JourneyIR and a protocol run result.
 *
 * Per ADR-0174 C.7/C.9, this is the canonical generator signature. The
 * legacy `ProtocolDefinition` authoring shape and the migration adapter
 * have been retired (ADR-0174 C.11 closed at M3.5 exit). Callers pass a
 * `JourneyIR` v2 directly.
 *
 * This is a data-driven report based on measured metrics (timing, pass/fail).
 * Friction scores and qualitative observations require LLM post-processing
 * which is NOT done here — this generates the raw audit data as markdown.
 */
export function generateAuditFromIR(
  ir: JourneyIR,
  output: ProtocolTestOutput,
  outputDir: string = path.resolve(process.cwd(), "../../docs/audits"),
): string {
  fs.mkdirSync(outputDir, { recursive: true });

  const date = new Date().toISOString().slice(0, 10);
  const passed = output.steps.filter((s) => s.status === "passed").length;
  const failed = output.steps.filter((s) => s.status !== "passed").length;

  const lines: string[] = [
    "---",
    `title: "UX Audit: ${ir.title}"`,
    `protocol_id: ${ir.slug}`,
    `generated: ${date}`,
    `status: draft`,
    "---",
    "",
    `# UX Audit — ${ir.title}`,
    "",
    `**Total duration:** ${output.friction_data.total_duration_ms}ms`,
    `**Steps:** ${output.steps.length}`,
    `**Passed:** ${passed}`,
    `**Failed:** ${failed}`,
    `**Slowest step:** ${output.friction_data.slowest_step}`,
    "",
    "## Per-Step Timing",
    "",
    "| Step | Title | Total ms | Action ms | Settle ms | Gate ms | Status |",
    "|------|-------|----------|-----------|-----------|---------|--------|",
  ];

  for (const step of output.steps) {
    lines.push(
      `| ${step.step_order} | ${step.title} | ${step.duration_ms} | ${step.timing.action_ms} | ${step.timing.settle_ms} | ${step.timing.gate_ms} | ${step.status} |`,
    );
  }

  lines.push("");

  if (output.friction_data.notes.length > 0) {
    lines.push("## Observations");
    lines.push("");
    for (const note of output.friction_data.notes) {
      lines.push(`- ${note}`);
    }
    lines.push("");
  }

  if (output.friction_data.failed_gates.length > 0) {
    lines.push("## Failed Gates");
    lines.push("");
    for (const gateId of output.friction_data.failed_gates) {
      const step = output.steps.find((s) => s.step_id === gateId);
      lines.push(`- **${gateId}**: ${step?.gate_result.error ?? "Unknown error"}`);
    }
    lines.push("");
  }

  lines.push("## Improvement Recommendations");
  lines.push("");
  lines.push("*[LLM post-processing required — run protocol:generate for AI-enriched analysis]*");
  lines.push("");
  lines.push("---");
  lines.push(`*Generated by Protocol Verification Engine ${date}*`);

  // `ir` is intentionally referenced via ir.title/ir.slug above — the
  // audit-generator historically ignored step content from the protocol
  // definition and read exclusively from the run output. That stays true
  // under JourneyIR.
  void ir;

  const content = lines.join("\n");
  const filePath = path.join(outputDir, `AUDIT-${ir.slug}-${date}.md`);
  fs.writeFileSync(filePath, content, "utf-8");

  return filePath;
}
