import * as fs from "fs";
import * as path from "path";
import type { ProtocolTestOutput } from "../protocols/types";
import type { ProtocolDefinition } from "../protocols/schema";

/**
 * Generates a UX audit report from protocol run timing data.
 *
 * This is a data-driven report based on measured metrics (timing, pass/fail).
 * Friction scores and qualitative observations require LLM post-processing
 * which is NOT done here — this generates the raw audit data as markdown.
 */
export function generateAudit(
  protocol: ProtocolDefinition,
  output: ProtocolTestOutput,
  outputDir: string = path.resolve(process.cwd(), "../../docs/audits"),
): string {
  fs.mkdirSync(outputDir, { recursive: true });

  const date = new Date().toISOString().slice(0, 10);
  const passed = output.steps.filter((s) => s.status === "passed").length;
  const failed = output.steps.filter((s) => s.status !== "passed").length;

  const lines: string[] = [
    "---",
    `title: "UX Audit: ${protocol.name}"`,
    `protocol_id: ${protocol.id}`,
    `generated: ${date}`,
    `status: draft`,
    "---",
    "",
    `# UX Audit — ${protocol.name}`,
    "",
    `**Total duration:** ${output.friction_data.total_duration_ms}ms`,
    `**Steps:** ${output.steps.length}`,
    `**Passed:** ${passed}`,
    `**Failed:** ${failed}`,
    `**Slowest step:** ${output.friction_data.slowest_step}`,
    "",
    "## Per-Step Timing",
    "",
    "| Step | Title | Total ms | Action ms | Settle ms | Gate ms | Status |",
    "|------|-------|----------|-----------|-----------|---------|--------|",
  ];

  for (const step of output.steps) {
    lines.push(
      `| ${step.step_order} | ${step.title} | ${step.duration_ms} | ${step.timing.action_ms} | ${step.timing.settle_ms} | ${step.timing.gate_ms} | ${step.status} |`,
    );
  }

  lines.push("");

  if (output.friction_data.notes.length > 0) {
    lines.push("## Observations");
    lines.push("");
    for (const note of output.friction_data.notes) {
      lines.push(`- ${note}`);
    }
    lines.push("");
  }

  if (output.friction_data.failed_gates.length > 0) {
    lines.push("## Failed Gates");
    lines.push("");
    for (const gateId of output.friction_data.failed_gates) {
      const step = output.steps.find((s) => s.step_id === gateId);
      lines.push(`- **${gateId}**: ${step?.gate_result.error ?? "Unknown error"}`);
    }
    lines.push("");
  }

  lines.push("## Improvement Recommendations");
  lines.push("");
  lines.push("*[LLM post-processing required — run protocol:generate for AI-enriched analysis]*");
  lines.push("");
  lines.push("---");
  lines.push(`*Generated by Protocol Verification Engine ${date}*`);

  const content = lines.join("\n");
  const filePath = path.join(outputDir, `AUDIT-${protocol.id}-${date}.md`);
  fs.writeFileSync(filePath, content, "utf-8");

  return filePath;
}
