/**
 * MySalaryListClient — lønnsgrunnlag PDF history list for the Min Lønn page.
 *
 * Fetches the current employee's historical lønnsgrunnlag export events
 * (payroll.export_event where format='pdf' + profile_id matches current user).
 * Renders a card per event with a link to the detail viewer.
 *
 * Route: Embedded in /dashboard/my-salary as an additional panel below the
 * existing payslip columns. Each row links to
 * /dashboard/my-salary/{lonnsgrunnlagId}.
 *
 * ADR-0151: profile_id resolved server-side via RLS (anon client uses auth.uid()).
 * ADR-0133: web-only read surface; mobile reads via Wave D.
 * L-0177: empty list → empty state card, not throw.
 * Nordic Split: CSS variables only. shadcn Card, Badge, Button, Skeleton.
 *
 * L-0176 compliance: docstring written after body verified.
 */
"use client";

import type { JSX } from "react";
import { useMemo } from "react";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { nb } from "date-fns/locale";
import { useQuery } from "@tanstack/react-query";
import { createClient } from "@smartout/supabase/client";
import { FileText, Download } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";

// ─── Type ────────────────────────────────────────────────────────────────────

/**
 * Subset of payroll.export_event columns used in this view.
 * Uses `exported_by` (the actor who triggered the PDF generation) to scope
 * the employee's own list. `export_format` identifies PDF events.
 * `started_at` is the canonical timestamp column for ordering.
 *
 * Note: When Wave B ships its admin-generated per-profile export_line rows,
 * this query may be extended to join export_event + export_line to show PDFs
 * generated by an admin on behalf of this employee.
 */
type LonnsgrunnlagEvent = {
  id: string;
  period_id: string;
  export_format: string;
  status: string;
  started_at: string;
  exported_by: string;
};

// ─── Data fetching ───────────────────────────────────────────────────────────

async function fetchMyLonnsgrunnlagEvents(): Promise<LonnsgrunnlagEvent[]> {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  // Resolve current employee's profile_id
  const { data: profile, error: profileErr } = await supabase
    .from("profile")
    .select("profile_id")
    .eq("user_id", user.id)
    .eq("is_active", true)
    .limit(1)
    .maybeSingle();

  if (profileErr) throw profileErr;
  if (!profile?.profile_id) return [];

  // Fetch export_events where export_format='pdf' triggered by this employee.
  // RLS on payroll.export_event scopes to the employee's workspace automatically.
  // exported_by = profile_id of the actor who triggered the PDF export
  // (for employee self-service: same as their own profile_id).
  const { data, error } = await supabase
    .schema("payroll")
    .from("export_event")
    .select("id, period_id, export_format, status, started_at, exported_by")
    .eq("exported_by", profile.profile_id)
    .eq("export_format", "pdf")
    .eq("status", "completed")
    .order("started_at", { ascending: false })
    .limit(50);

  if (error) throw error;

  return (data ?? []) as LonnsgrunnlagEvent[];
}

function useLonnsgrunnlagEvents() {
  return useQuery<LonnsgrunnlagEvent[]>({
    queryKey: ["my-salary", "lonnsgrunnlag-events"],
    queryFn: fetchMyLonnsgrunnlagEvents,
    staleTime: 5 * 60 * 1000, // 5 minutes — PDF events change rarely
    retry: 1,
  });
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatExportedAt(iso: string): string {
  try {
    return format(parseISO(iso), "d. MMM yyyy HH:mm", { locale: nb });
  } catch {
    return iso;
  }
}

// ─── Row component ───────────────────────────────────────────────────────────

function LonnsgrunnlagRow({ event }: { event: LonnsgrunnlagEvent }): JSX.Element {
  return (
    <li className="border-border flex items-center gap-3 border-b py-3 last:border-0">
      <FileText className="text-muted-foreground mt-0.5 h-4 w-4 shrink-0" />
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-foreground text-sm font-medium">Lønnsgrunnlag</span>
          <Badge variant="outline" className="text-xs">
            PDF
          </Badge>
        </div>
        <p className="text-muted-foreground mt-0.5 text-xs">{formatExportedAt(event.started_at)}</p>
      </div>
      <Link
        href={`/dashboard/my-salary/${event.id}`}
        className="text-primary hover:text-primary/80 flex shrink-0 items-center gap-1 text-xs font-medium transition-colors"
        aria-label="Vis lønnsgrunnlag PDF"
      >
        <Download className="h-3 w-3" />
        Vis PDF
      </Link>
    </li>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export function MySalaryListClient(): JSX.Element {
  const { data: events, isLoading } = useLonnsgrunnlagEvents();

  const sortedEvents = useMemo(() => events ?? [], [events]);

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-base">Lønnsgrunnlag (PDF)</CardTitle>
      </CardHeader>
      <CardContent className="px-4 pb-4">
        {isLoading ? (
          <div className="space-y-3 pt-1">
            {Array.from({ length: 3 }).map((_, i) => (
              <Skeleton key={i} className="h-12 w-full rounded-lg" />
            ))}
          </div>
        ) : sortedEvents.length === 0 ? (
          <p className="text-muted-foreground py-4 text-center text-sm">
            Ingen lønnsgrunnlag tilgjengelig ennå.
          </p>
        ) : (
          <ul>
            {sortedEvents.map((event) => (
              <LonnsgrunnlagRow key={event.id} event={event} />
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}
