/**
 * All Norwegian UI strings for the mobile app, centralized.
 * Every screen imports from here — no hardcoded strings in components.
 * i18n via @smartout/i18n planned for V2.
 */
export const strings = {
  tabs: {
    home: "Hjem",
    shifts: "Vakter",
    chat: "Chat",
    me: "Meg",
  },
  home: {
    greeting: "Hei",
    goodMorning: "God morgen",
    goodAfternoon: "God ettermiddag",
    goodEvening: "God kveld",
    goodNight: "God natt",
    nextShift: "Neste vakt",
    noShift: "Ingen kommende vakter",
    onShift: "På vakt",
    shiftDone: "Vakt avsluttet",
    shiftStartedAgo: "Vakten din begynte for",
    minutesAgo: "min siden",
    unreadMessages: "uleste meldinger",
  },
  shift: {
    confirm: "Bekreft vakt",
    punchIn: "Stemple inn",
    punchOut: "Stemple ut",
    confirmed: "Bekreftet",
    colleagues: "Kolleger",
    leader: "Leder",
    dayInfo: "Daginfo",
    position: "Posisjon",
  },
  tasks: {
    title: "Oppgaver",
    noTasks: "Alt klart.",
    reportDeviation: "Rapporter avvik",
    dueSoon: "Forfaller snart",
    completed: "Fullført",
  },
  cleaning: {
    title: "Renholdssjekk",
    signAndComplete: "Signer og fullfør",
    progress: (done: number, total: number) => `${done} av ${total} fullført`,
    flagDeviation: "Rapporter avvik",
    takePhoto: "Ta bilde",
    completed: "Fullført",
    required: "Påkrevd",
  },
  chat: {
    channels: "Kanaler",
    directMessages: "Direktmeldinger",
    activeShift: "Aktiv vakt",
    placeholder: "Skriv melding...",
    noMessages: "Ingen meldinger ennå. Start samtalen!",
  },
  auth: {
    welcome: "Velkommen til Smartout",
    invite: "Jeg har en invitasjon",
    code: "Jeg har en kode",
    search: "Finn min arbeidsplass",
    enterCode: "Skriv inn 6-sifret kode",
    searchPlaceholder: "Søk etter arbeidsplass...",
    requestSent: "Forespørsel sendt",
    waitingForApproval: "Du får beskjed når admin godkjenner.",
    isThisCorrect: "Er dette riktig?",
    joinWorkspace: "Bli med i",
    verifyPhone: "Bekreft telefonnummer",
    enterOtp: "Skriv inn koden du fikk på SMS",
  },
  sync: {
    syncing: "Synkroniserer",
    waiting: "poster venter",
    failed: "mislyktes",
    retry: "Prøv igjen",
    synced: "Alt synkronisert",
    noConnection: "ingen tilkobling",
  },
  handoff: {
    title: "Overlevering",
    placeholder: "Skriv overlevering...",
    send: "Send",
    notSubmitted: "Ej innlevert",
  },
  hours: {
    title: "Bekreft timer",
    planned: "Planlagt",
    registered: "Registrert",
    break: "Pause",
    confirm: "Bekreft",
    dispute: "Bestrid",
  },
  me: {
    profile: "Profil",
    settings: "Innstillinger",
    logout: "Logg ut",
    logoutConfirm: "Er du sikker pa at du vil logge ut?",
    deleteAccount: "Slett konto",
    deleteAccountWarning:
      "Dette sletter kontoen din permanent. All data — profil, vakter, meldinger og opplæring — fjernes og kan ikke gjenopprettes.",
    deleteAccountConfirmTitle: "Bekreft sletting",
    deleteAccountConfirmMessage: 'Skriv "SLETT" for å bekrefte permanent sletting av kontoen din.',
    deleteAccountConfirmWord: "SLETT",
    deleteAccountSuccess: "Kontoen din er slettet.",
    deleteAccountError: "Kunne ikke slette kontoen. Kontakt support.",
    callLeader: "Ring leder",
    callLeaderNoPhone: "Ingen leder er tilgjengelig. Bruk chat.",
    callLeaderUnsupported: "Kan ikke åpne telefon på denne enheten.",
    trainingLocked: "Trening & sertifikat",
    comingSoon: "Kommer snart",
    notifications: "Varsler",
    pushNotifications: "Push-varsler",
    role: "Rolle",
    department: "Avdeling",
  },
  botsson: {
    title: "Mr. Botsson",
    greetingNoShift: "Hei! Hva kan jeg hjelpe med?",
    greetingBeforeShift: "Hei! Du har vakt snart. Hva trenger du?",
    greetingDuringShift: "Hei! Du er p\u00e5 vakt. Hva trenger du hjelp med?",
    greetingAfterShift: "Vakt avsluttet. Trenger du hjelp med noe?",
  },
  common: {
    send: "Send",
    cancel: "Avbryt",
    save: "Lagre",
    done: "Ferdig",
    loading: "Laster...",
    error: "Noe gikk galt",
    tryAgain: "Prøv igjen",
  },
  call: {
    youSuffix: "(Du)",
    speaking: "snakker",
    silent: "stille",
    waitingForParticipants: "Venter p\u00e5 deltakere\u2026",
    participants: "deltakere",
    minimize: "Minimer",
    camera: "Kamera",
    endCall: "Avslutt",
    mute: "Demp",
    unmute: "Lyd p\u00e5",
    listenOnly: "Kun lytting",
    inCall: "I samtale",
    startCall: "Start samtale",
  },
  payroll: {
    title: "Lønn & fravær",
    /** Payroll hub — read-only employee screens */
    hubIntro: "Velg hva du vil se. Alt her er kun til lesing.",
    supplementTemplateLead:
      "Eksempel for en typisk kveldsvakt (15:00–23:00). Faktiske tillegg avhenger av planlagt vakt.",
    absence: "Fravær",
    absenceBalance: "Fraværssaldo",
    timebank: "Timebank",
    myPay: "Min lønn",
    seeAll: "Se alt",
    // Trust labels
    preliminaryEstimate: "Foreløpig estimat",
    registeredTime: "Registrert tid",
    settledInPayroll: "Avregnet i lønn",
    estimateDisclaimer:
      "Foreløpig estimat basert på planlagt tid og gjeldende satser. Endelig beløp kan avvike.",
    // Absence types
    vacation: "Ferie",
    selfReported: "Egenmelding",
    careDays: "Omsorgsdager",
    // Balance
    daysRemaining: "dager igjen",
    of: "av",
    balanceAfter: "Saldo etter",
    workdays: "virkedager",
    available: "Tilgjengelig",
    lastUpdated: "Sist oppdatert",
    // Request
    requestAbsence: "Søk om fravær",
    absenceType: "Type fravær",
    period: "Periode",
    comment: "Kommentar",
    commentOptional: "Kommentar (valgfritt)",
    sendRequest: "Send søknad",
    myRequests: "Mine søknader",
    pending: "Venter",
    approved: "Godkjent",
    rejected: "Avslått",
    cancelled: "Kansellert",
    cancelRequest: "Kanseller",
    requestFailedTitle: "Søknad feilet",
    requestFailed: "Noe gikk galt. Prøv igjen.",
    overlapWarning: "Overlapper med eksisterende fravær",
    insufficientBalance: "Ikke nok dager tilgjengelig",
    // Payslip
    lastPaid: "Sist utbetalt",
    netPay: "Utbetalt",
    grossPay: "Bruttolønn",
    baseSalary: "Grunnlønn",
    supplements: "Tillegg",
    overtime: "Overtid",
    taxDeduction: "Skattetrekk",
    workHours: "Arbeidstimer",
    absenceDeduction: "Fraværstrekk",
    downloadPdf: "Last ned PDF",
    previousPeriods: "Tidligere",
    specification: "Spesifikasjon",
    // Supplements
    eveningSupplement: "Kveldstillegg",
    weekendSupplement: "Helgetillegg",
    holidaySupplement: "Helligdagstillegg",
    todaysSupplements: "Dagens tillegg",
    // Home card
    earnedToday: "Opptjent i dag",
    earnedThisShift: "Opptjent denne vakten",
    totalSoFar: "Totalt så langt",
    totalEarned: "Totalt opptjent",
    // Timebank
    availableForToil: "Tilgjengelig for avspasering",
    recentMovements: "Siste bevegelser",
    hours: "timer",
    // Empty states
    noPayData: "Ingen lønnsdata ennå",
    noPayslips:
      "Ingen lønnsslipp tilgjengelig ennå. Din første lønnsslipp vises her etter første lønnskjøring.",
    noQuotas: "Ingen fraværskvoter er satt opp ennå. Kontakt din leder.",
    noTimebank: "Ingen timer i timebanken ennå.",
    // Error states
    loadError: "Kunne ikke laste fraværssaldo",
    loadErrorTimebank: "Kunne ikke laste timebank",
    loadErrorPayslip: "Kunne ikke laste lønnsslipp",
    // Fallback labels
    unknownType: "Ukjent type",
    // Balance display
    days: "dager",
    // Vacation strip
    vacationDaysLeftIn: "Feriedager igjen i",
    // Absence request form
    fromDate: "Fra dato",
    toDate: "Til dato",
    commentPlaceholder: "F.eks. planlagt ferie uke 28-30",
  },
} as const;

export type Strings = typeof strings;
