#!/bin/bash
# ============================================
# sync-env-to-droplet.sh — 1Password → DigitalOcean env sync
#
# Reads production secrets from smartout_ai_prod vault and writes
# infra/.env on the droplet. Can run locally (via SSH) or on the
# droplet directly (if 1Password Service Account is configured).
#
# Usage:
#   ./infra/scripts/sync-env-to-droplet.sh              # write to local infra/.env
#   ./infra/scripts/sync-env-to-droplet.sh --remote      # write to droplet via SSH
#   ./infra/scripts/sync-env-to-droplet.sh --dry-run     # preview only
#
# Prerequisites:
#   - OP_SERVICE_ACCOUNT_TOKEN set, OR eval "$(op signin)"
#   - SSH access to droplet (for --remote mode)
# ============================================

set -euo pipefail

DRY_RUN=false
REMOTE=false
# TODO: Move to SSH config alias or env var for portability
DROPLET_HOST="${DROPLET_HOST:-root@164.92.176.42}"
DROPLET_ENV_PATH="${DROPLET_ENV_PATH:-/root/dev/smartout.ai/infra/.env}"

for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
    --remote) REMOTE=true ;;
  esac
done

# Verify 1Password access
if ! op whoami >/dev/null 2>&1; then
  echo "ERROR: 1Password not authenticated."
  echo "Set OP_SERVICE_ACCOUNT_TOKEN or run: eval \"\$(op signin)\""
  exit 1
fi
echo "1Password: authenticated"

# Production env var manifest
# Format: KEY|op://vault/item/field
MANIFEST=(
  "SUPABASE_URL|op://smartout_ai_prod/Supabase/url"
  "SUPABASE_ANON_KEY|op://smartout_ai_prod/Supabase/anon_key"
  "SUPABASE_SERVICE_ROLE_KEY|op://smartout_ai_prod/Supabase/service_role_key"
  "ENGINE_URL|op://smartout_ai_prod/Stage-Engine/url"
  "STAGE_ENGINE_API_KEY|op://smartout_ai_prod/Stage-Engine/api_key"
  "ULTRAVOX_API_KEY|op://smartout_ai_prod/Ultravox/api_key"
  "OPENROUTER_API_KEY|op://smartout_ai_prod/OpenRouter/api_key"
  "SCRAPLING_AUTH_TOKEN|op://smartout_ai_prod/Scrapling/auth_token"
  "SERPER_API_KEY|op://smartout_ai_prod/Serper/api_key"
  "CONTRACT_SERVICE_KEY|op://smartout_ai_prod/SmartOut/contract_service_key"
  "DOCUSEAL_API_KEY|op://smartout_ai_prod/DocuSeal/api_key"
  "DOCUSEAL_WEBHOOK_SECRET|op://smartout_ai_prod/DocuSeal/webhook_secret"
  "N8N_ENCRYPTION_KEY|op://smartout_ai_prod/n8n/encryption_key"
  "N8N_BASIC_AUTH_USER|op://smartout_ai_prod/n8n/basic_auth_user"
  "N8N_BASIC_AUTH_PASSWORD|op://smartout_ai_prod/n8n/basic_auth_password"
)

# Resolve all values
echo "Resolving ${#MANIFEST[@]} variables from smartout_ai_prod vault..."
ENV_CONTENT="# Generated by sync-env-to-droplet.sh — $(date -Iseconds)\n# DO NOT EDIT MANUALLY. Re-run this script to update.\n"
FAILED=0

for entry in "${MANIFEST[@]}"; do
  IFS='|' read -r key op_ref <<< "$entry"
  value=$(op read "$op_ref" 2>/dev/null) || {
    echo "  FAIL  $key ($op_ref)"
    FAILED=1
    continue
  }
  echo "  OK    $key"
  ENV_CONTENT+="${key}=${value}\n"
done

# Static values (not in vault)
ENV_CONTENT+="NODE_ENV=production\n"
ENV_CONTENT+="LOG_LEVEL=info\n"
ENV_CONTENT+="APP_URL=https://app.smartout.ai\n"

if [ "$FAILED" -eq 1 ]; then
  echo ""
  echo "ERROR: Some variables failed to resolve. Aborting."
  exit 1
fi

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "=== DRY RUN — would write: ==="
  echo -e "$ENV_CONTENT" | sed 's/=.*/=<redacted>/'
  exit 0
fi

if [ "$REMOTE" = true ]; then
  echo ""
  echo "Writing to droplet: $DROPLET_HOST:$DROPLET_ENV_PATH"
  echo -e "$ENV_CONTENT" | ssh "$DROPLET_HOST" "cat > $DROPLET_ENV_PATH"
  echo "Done. Restart services with: ssh $DROPLET_HOST '/root/dev/smartout.ai/infra/scripts/deploy.sh'"
else
  LOCAL_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"
  echo ""
  echo "Writing to local: $LOCAL_PATH"
  echo -e "$ENV_CONTENT" > "$LOCAL_PATH"
  echo "Done."
fi
