/**
 * packages/ai/src/scheduler/solver/greedy.ts
 *
 * Greedy constraint-solver for the Smartout scheduler (V1).
 *
 * CONTRACT:
 *   - Pure, synchronous, deterministic. No DB calls. No async.
 *   - Same input twice → same output (including same solver_run_id? NO —
 *     solver_run_id is generated per call). Same input → same proposed_shifts
 *     order and same gap list. Only solver_run_id differs.
 *   - Tie-break: ORDER BY utilized_hours ASC, profile_id ASC per ADR-0307
 *     (precedent: apps/web/src/app/api/payroll/_shared.ts:93).
 *   - Output: SolverProposal — never direct DB writes. Caller (capability tool)
 *     persists as change_proposal via mutateWithGate (ADR-0309).
 *
 * ALGORITHM (greedy V1):
 *   1. Slice planning cycle into 1-hour time buckets per department.
 *   2. For each bucket, compute headcount_needed from demand score × 1
 *      (baseline productivity multiplier = 1 for V1; V2 uses workforce_ratio).
 *   3. Sort buckets: headcount DESC (tie-break: start_at ASC, department_id ASC).
 *   4. Per assignment slot (1..headcount_needed), already-assigned profiles
 *      tracked in this_run_shifts to avoid double-booking.
 *   5. Filter eligible profiles via eligibilityFor(); sort eligible by
 *      (utilized_hours ASC, profile_id ASC); pick lowest-utilized.
 *   6. If eligible profile found → ProposedShift. Else → Gap.
 *
 * SHA-256 hash of canonical input JSON stored as solver_inputs_hash for
 * determinism replay and audit (ADR-0309 §V1 Persistence Shape).
 *
 * ADR REFERENCES:
 *   ADR-0307 (greedy V1 algorithm)
 *   ADR-0309 (bundle proposal pattern — persistence is caller's responsibility)
 *   L-0247   (single-call mutateWithGate — solver is pure, no gating here)
 *   L-0248   (provenance in JSONB, not enum)
 */

import { createHash } from "node:crypto";
import { randomUUID } from "node:crypto";

import {
  eligibilityFor,
  type BlockerCode,
  type EligibilityProfile,
  type EligibilityShift,
  type ExistingShift,
  type Absence,
  type FrameworkRule,
  type EmploymentContract,
} from "../eligibility.js";

// ─── Public input/output types ────────────────────────────────────────────────

/**
 * A demand bucket: a 1-hour window in a department with a demand score.
 * `score` is a float (0..N) representing required headcount for this hour.
 * Caller derives from day_factor × hour_factor × baseline_headcount.
 */
export interface DemandBucket {
  department_id: string;
  /** ISO 8601 UTC start of this hour window. */
  start_at: string;
  /** ISO 8601 UTC end of this hour window (start_at + 1h). */
  end_at: string;
  /** Required headcount. Ceiling applied: Math.ceil(score). */
  score: number;
  /** Position/role required in this bucket. */
  position_id: string;
  role: string;
}

/**
 * A profile eligible for assignment. Solver receives pre-loaded context per profile.
 * Caller loads all profiles active in the workspace for the planning cycle.
 */
export interface SolverProfile {
  profile: EligibilityProfile;
  /** Total hours already booked (from existing_shifts + this_run commits so far).
   *  Solver updates utilized_hours as it assigns to maintain fairness ordering. */
  utilized_hours: number;
  /** Pre-loaded context for eligibilityFor(). Caller scopes to planning-cycle window. */
  existing_shifts: ExistingShift[];
  absences: Absence[];
  framework_rules: FrameworkRule[];
  active_contract: EmploymentContract | null;
}

/**
 * A shift proposed by the solver for a demand bucket assignment.
 * Mirrors ADR-0309 §V1 Persistence Shape `proposed_shifts[]` array element.
 */
export interface ProposedShift {
  /** UUID for this proposed shift (generated by solver). Not yet in DB. */
  shift_id_proposed: string;
  department_id: string;
  start_at: string;
  end_at: string;
  position_id: string;
  role: string;
  assigned_profile_id: string;
  rationale: string;
  /** Framework rule codes relevant to this assignment (for audit trail). */
  tariff_rule_ids: string[];
}

/**
 * A gap: a demand bucket where no eligible profile could be assigned.
 */
export interface SolverGap {
  department_id: string;
  start_at: string;
  end_at: string;
  position_id: string;
  role: string;
  /** Required headcount that could not be filled. */
  headcount_needed: number;
  /** Headcount actually filled before running out of eligible profiles. */
  headcount_filled: number;
  /** All distinct blockers encountered across all candidate evaluations. */
  blocker_codes: BlockerCode[];
}

/**
 * Solver inputs — everything the algorithm needs. Caller loads from cascade.
 * All fields required; fail-fast on undefined (L-0177).
 */
export interface SolverInput {
  /** Workspace scope. Required. */
  workspace_id: string;
  /** Planning cycle D1 envelope — defines the date range. */
  planning_cycle: {
    planning_cycle_id: string;
    department_id: string;
    starts_at: string;
    ends_at: string;
  };
  /** D4 demand buckets covering the cycle. */
  demand_buckets: DemandBucket[];
  /** D2 roster with pre-loaded eligibility context per profile. */
  profiles: SolverProfile[];
  /** D3 framework rules — used to build tariff_rule_ids in output (informational). */
  framework_rules: FrameworkRule[];
  /** D6 existing committed shifts in the cycle (solver will not double-assign). */
  existing_shifts: ExistingShift[];
}

/**
 * Solver output. Caller writes as a single change_proposal row (ADR-0309).
 */
export interface SolverProposal {
  /** greedy_v1 — algorithm version tag (stored in changes JSONB). */
  solver_version: "greedy_v1";
  /** UUID per run — changes each call. Stored in changes JSONB for audit. */
  solver_run_id: string;
  /** SHA-256 of canonical JSON of SolverInput (determinism key). */
  solver_inputs_hash: string;
  /** demand_coverage_pct × (1 - hour_variance_pct). Both in [0..1]. */
  objective_score: number;
  proposed_shifts: ProposedShift[];
  gaps: SolverGap[];
  /** 0..1 fraction: unfilled demand / total demand. V2 trigger: >0.30 over 2 cycles. */
  gap_rate: number;
}

// ─── Main solver function ─────────────────────────────────────────────────────

/**
 * Greedy constraint-solver. Pure, deterministic (same input → same assignment
 * sequence; solver_run_id differs per call by design for audit uniqueness).
 *
 * See module docstring for full algorithm description.
 */
export function solveGreedy(input: SolverInput): SolverProposal {
  validateInput(input);

  const solverRunId = randomUUID();
  const inputsHash = hashInput(input);

  // ── Mutable runtime state ──────────────────────────────────────────────────
  // per-profile utilized_hours, seeded from input and updated as assignments commit.
  const utilized = new Map<string, number>(
    input.profiles.map((sp) => [sp.profile.profile_id, sp.utilized_hours]),
  );

  // Shifts assigned in THIS run — needed to prevent double-booking across buckets.
  const thisRunShifts = new Map<string, ExistingShift[]>(); // profile_id → shifts

  const proposed_shifts: ProposedShift[] = [];
  const gaps: SolverGap[] = [];

  // ── Step 1+2+3: sort buckets by demand descending, tie-break start_at + dept ─
  const sortedBuckets = sortBuckets(input.demand_buckets);

  // ── Step 4-6: greedy assignment ────────────────────────────────────────────
  for (const bucket of sortedBuckets) {
    const headcountNeeded = Math.ceil(bucket.score);
    if (headcountNeeded <= 0) continue;

    let headcountFilled = 0;
    const allBlockers = new Set<BlockerCode>();

    for (let slot = 0; slot < headcountNeeded; slot++) {
      // Sort eligible candidates by (utilized_hours ASC, profile_id ASC) — deterministic.
      const sorted = sortCandidates(input.profiles, utilized);

      let assigned = false;
      for (const sp of sorted) {
        const profileId = sp.profile.profile_id;

        // Build shift candidate for eligibility check.
        const candidate: EligibilityShift = {
          shift_id: `proposed-${solverRunId}-${bucket.department_id}-${bucket.start_at}-slot${slot}`,
          workspace_id: input.workspace_id,
          role: bucket.role,
          start_at: bucket.start_at,
          end_at: bucket.end_at,
          duration_hours: hoursBetween(bucket.start_at, bucket.end_at),
        };

        // Combine pre-loaded existing shifts + what this run has already assigned.
        const runShifts = thisRunShifts.get(profileId) ?? [];
        const combinedExisting: ExistingShift[] = [...sp.existing_shifts, ...runShifts];

        const result = eligibilityFor(sp.profile, candidate, {
          existing_shifts: combinedExisting,
          absences: sp.absences,
          framework_rules: sp.framework_rules,
          active_contract: sp.active_contract,
        });

        if (!result.eligible) {
          for (const b of result.blockers) allBlockers.add(b);
          continue;
        }

        // Assign: create proposed shift, update utilization.
        const proposedId = randomUUID();
        const shiftDuration = hoursBetween(bucket.start_at, bucket.end_at);

        proposed_shifts.push({
          shift_id_proposed: proposedId,
          department_id: bucket.department_id,
          start_at: bucket.start_at,
          end_at: bucket.end_at,
          position_id: bucket.position_id,
          role: bucket.role,
          assigned_profile_id: profileId,
          rationale: `lowest-utilized eligible profile (utilized_hours=${utilized.get(profileId)?.toFixed(1)})`,
          tariff_rule_ids: collectTariffRuleIds(input.framework_rules),
        });

        // Update runtime utilization + this-run shift list.
        const prev = utilized.get(profileId) ?? 0;
        utilized.set(profileId, prev + shiftDuration);

        const existingRun = thisRunShifts.get(profileId) ?? [];
        thisRunShifts.set(profileId, [
          ...existingRun,
          {
            shift_id: proposedId,
            start_at: bucket.start_at,
            end_at: bucket.end_at,
            duration_hours: shiftDuration,
          },
        ]);

        headcountFilled++;
        assigned = true;
        break; // move to next slot
      }

      if (!assigned) {
        // No eligible profile for this slot — record and move on.
        // We'll collect all slots into a single gap entry below.
      }
    }

    const unfilled = headcountNeeded - headcountFilled;
    if (unfilled > 0) {
      gaps.push({
        department_id: bucket.department_id,
        start_at: bucket.start_at,
        end_at: bucket.end_at,
        position_id: bucket.position_id,
        role: bucket.role,
        headcount_needed: headcountNeeded,
        headcount_filled: headcountFilled,
        blocker_codes: [...allBlockers],
      });
    }
  }

  // ── Objective score ────────────────────────────────────────────────────────
  const { objectiveScore, gapRate } = computeObjective(
    input.demand_buckets,
    proposed_shifts,
    input.profiles,
    utilized,
  );

  return {
    solver_version: "greedy_v1",
    solver_run_id: solverRunId,
    solver_inputs_hash: inputsHash,
    objective_score: objectiveScore,
    proposed_shifts,
    gaps,
    gap_rate: gapRate,
  };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function validateInput(input: SolverInput): void {
  if (!input.workspace_id || input.workspace_id.trim() === "") {
    throw new Error("solveGreedy: workspace_id is required (L-0177)");
  }
  if (!input.planning_cycle) {
    throw new Error("solveGreedy: planning_cycle is required");
  }
  if (!Array.isArray(input.demand_buckets)) {
    throw new Error("solveGreedy: demand_buckets must be an array");
  }
  if (!Array.isArray(input.profiles)) {
    throw new Error("solveGreedy: profiles must be an array");
  }
}

/**
 * Sort buckets: headcount DESC, then start_at ASC, then department_id ASC.
 * Deterministic: same input → same sort order.
 */
function sortBuckets(buckets: DemandBucket[]): DemandBucket[] {
  return [...buckets].sort((a, b) => {
    const headA = Math.ceil(a.score);
    const headB = Math.ceil(b.score);
    if (headB !== headA) return headB - headA;
    const startCmp = a.start_at.localeCompare(b.start_at);
    if (startCmp !== 0) return startCmp;
    return a.department_id.localeCompare(b.department_id);
  });
}

/**
 * Sort profiles by (utilized_hours ASC, profile_id ASC) — deterministic tie-break.
 * Per ADR-0307 + apps/web/src/app/api/payroll/_shared.ts:93 precedent.
 */
function sortCandidates(profiles: SolverProfile[], utilized: Map<string, number>): SolverProfile[] {
  return [...profiles].sort((a, b) => {
    const hoursA = utilized.get(a.profile.profile_id) ?? 0;
    const hoursB = utilized.get(b.profile.profile_id) ?? 0;
    if (hoursA !== hoursB) return hoursA - hoursB;
    return a.profile.profile_id.localeCompare(b.profile.profile_id);
  });
}

/** Returns fractional hours between two ISO 8601 datetime strings. */
function hoursBetween(startAt: string, endAt: string): number {
  return (new Date(endAt).getTime() - new Date(startAt).getTime()) / 3_600_000;
}

/**
 * Collect tariff rule codes relevant to scheduling assignments.
 * Returns codes for tariff_min_rest_hours and aml_daily_max_hours rules.
 */
function collectTariffRuleIds(rules: FrameworkRule[]): string[] {
  // In the context here FrameworkRule is the eligibility type with rule_type strings.
  // We return the rule_type strings as identifiers; callers can map to DB IDs via
  // their loaded framework_rule rows.
  return rules
    .filter(
      (r) =>
        r.rule_type === "tariff_min_rest_hours" ||
        r.rule_type === "aml_daily_max_hours" ||
        r.rule_type === "aml_weekly_max_hours",
    )
    .map((r) => r.rule_type);
}

/**
 * Compute objective score and gap rate.
 * objective_score = demand_coverage_pct × (1 - normalized_hour_variance).
 * gap_rate = total unfilled headcount / total demanded headcount.
 */
function computeObjective(
  buckets: DemandBucket[],
  proposed: ProposedShift[],
  profiles: SolverProfile[],
  utilized: Map<string, number>,
): { objectiveScore: number; gapRate: number } {
  const totalDemand = buckets.reduce((sum, b) => sum + Math.ceil(b.score), 0);
  const totalFilled = proposed.length;
  const coveragePct = totalDemand > 0 ? totalFilled / totalDemand : 1.0;

  // Hour variance across profiles (normalized to [0..1]).
  const hours = profiles.map((sp) => utilized.get(sp.profile.profile_id) ?? 0);
  const meanHours = hours.length > 0 ? hours.reduce((s, h) => s + h, 0) / hours.length : 0;
  const variance =
    hours.length > 1 ? hours.reduce((s, h) => s + Math.pow(h - meanHours, 2), 0) / hours.length : 0;
  const stdDev = Math.sqrt(variance);
  // Normalize: if mean is 0 variance is 0. Cap normalized to [0..1].
  const normalizedVariance = meanHours > 0 ? Math.min(stdDev / meanHours, 1.0) : 0;
  const fairnessFactor = 1 - normalizedVariance;

  const objectiveScore = Math.round(coveragePct * fairnessFactor * 100) / 100;
  const gapRate =
    totalDemand > 0 ? Math.round(((totalDemand - totalFilled) / totalDemand) * 100) / 100 : 0;

  return { objectiveScore, gapRate };
}

/**
 * SHA-256 hash of a canonical JSON representation of SolverInput.
 * Used as solver_inputs_hash for audit and determinism replay.
 * workspace_id + planning_cycle + demand_buckets + profile IDs (not contexts, which may grow).
 */
function hashInput(input: SolverInput): string {
  const canonical = JSON.stringify({
    workspace_id: input.workspace_id,
    planning_cycle_id: input.planning_cycle.planning_cycle_id,
    demand_buckets: input.demand_buckets
      .map((b) => ({
        department_id: b.department_id,
        start_at: b.start_at,
        end_at: b.end_at,
        score: b.score,
        position_id: b.position_id,
        role: b.role,
      }))
      .sort(
        (a, b) =>
          a.start_at.localeCompare(b.start_at) || a.department_id.localeCompare(b.department_id),
      ),
    profile_ids: input.profiles.map((sp) => sp.profile.profile_id).sort(),
  });
  return createHash("sha256").update(canonical).digest("hex");
}
