export type ApiEndpoint = {
  path: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  category:
    | "auth"
    | "dashboard"
    | "platform-admin"
    | "webhook"
    | "system"
    | "contract-service"
    | "edge-function"
    | "public-api";
  service: "web" | "contract-service" | "supabase" | "workspace-api";
  description: string;
  auth: "public" | "anon" | "authenticated" | "super-admin" | "service-role" | "api-key";
  status: "active" | "planned" | "deprecated";
};

export const apiRegistry: ApiEndpoint[] = [
  // ── System ──
  {
    path: "/api/health",
    method: "GET",
    category: "system",
    service: "web",
    description: "Service health check with DB ping and memory stats",
    auth: "public",
    status: "active",
  },
  {
    path: "/api/telemetry",
    method: "POST",
    category: "system",
    service: "web",
    description: "PostHog telemetry beacon proxy",
    auth: "authenticated",
    status: "active",
  },

  // ── Dashboard / AI ──
  {
    path: "/api/onboarding-agent",
    method: "POST",
    category: "dashboard",
    service: "web",
    description: "Onboarding AI agent (Vercel AI SDK streaming)",
    auth: "authenticated",
    status: "active",
  },
  {
    path: "/api/contract-agent",
    method: "POST",
    category: "dashboard",
    service: "web",
    description: "Contract AI assistant (Vercel AI SDK streaming)",
    auth: "super-admin",
    status: "active",
  },

  // ── Platform Admin ──
  {
    path: "/api/platform-admin/health/status",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Aggregated health status for all services",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/metrics",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Platform metrics (daily KPIs)",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/workspaces",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "List all workspaces with stats",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/workspaces/[id]",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Get workspace detail with members",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/workspaces/[id]/impersonate",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Start workspace impersonation session",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/users",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "List all users with workspace counts",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/users/toggle-super-admin",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Grant or revoke super admin access",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/billing",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Billing overview with Stripe sync status",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/audit",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Platform audit log entries",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/content",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Landing page CMS content",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/content",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Update landing page CMS content",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/contracts",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "List contracts (proxy to contract service)",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/contracts",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Create contract (proxy to contract service)",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/contracts/[id]/send",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Send contract for signing via DocuSeal",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/contracts/[id]/cancel",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Cancel a pending contract",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/contracts/[id]/remind",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Send reminder for unsigned contract",
    auth: "super-admin",
    status: "active",
  },

  // ── Key Management ──
  {
    path: "/api/platform-admin/keys",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "List all API keys with workspace names",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/keys",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Create new API key (returns plaintext once)",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/keys/[id]",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Get API key detail with rotation versions and usage",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/keys/[id]/rotate",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Rotate API key (versioned dual-key with grace period)",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/keys/[id]/revoke",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Revoke all versions of an API key",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/keys/[id]/usage",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "Get hourly usage buckets for an API key",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/secrets",
    method: "GET",
    category: "platform-admin",
    service: "web",
    description: "List external secrets metadata (no decrypted values)",
    auth: "super-admin",
    status: "active",
  },
  {
    path: "/api/platform-admin/secrets",
    method: "POST",
    category: "platform-admin",
    service: "web",
    description: "Store external secret in Vault with metadata",
    auth: "super-admin",
    status: "active",
  },

  // ── Webhooks ──
  {
    path: "/api/webhooks/docuseal",
    method: "POST",
    category: "webhook",
    service: "web",
    description: "DocuSeal contract signing webhook",
    auth: "public",
    status: "active",
  },
  {
    path: "/api/webhooks/stripe",
    method: "POST",
    category: "webhook",
    service: "web",
    description: "Stripe billing webhook",
    auth: "public",
    status: "planned",
  },

  // ── Edge Functions ──
  {
    path: "/functions/v1/activate-workspace",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Activate a workspace after onboarding",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/analyze-workspace",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "AI-powered workspace analysis and scoring",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/contract-lifecycle",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Contract state machine transitions",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/api/admin/invite",
    method: "POST",
    category: "dashboard",
    service: "web",
    description: "Browser BFF for invitation creation (replaces Edge Function per ADR-0179)",
    auth: "authenticated",
    status: "active",
  },
  {
    path: "/functions/v1/extract-workspace-data",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Extract structured data from workspace scrape",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/finalize-workspace",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Finalize workspace setup with generated data",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/gather-workspace-intelligence",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Gather intelligence from multiple sources",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/health-check",
    method: "GET",
    category: "edge-function",
    service: "supabase",
    description: "Supabase Edge Functions health check",
    auth: "public",
    status: "active",
  },
  {
    path: "/functions/v1/scrape-raw-data",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Raw website scraping for workspace analysis",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/watchdog-integrity",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Data integrity checks (orphans, broken refs)",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/watchdog-uptime",
    method: "GET",
    category: "edge-function",
    service: "supabase",
    description: "Uptime monitoring ping",
    auth: "public",
    status: "active",
  },
  {
    path: "/functions/v1/validate-api-key",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Validate API key or JWT, return auth context with rate limiting",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/cleanup-api-keys",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Cron: revoke expired grace-period API keys",
    auth: "service-role",
    status: "active",
  },
  {
    path: "/functions/v1/web-search-intelligence",
    method: "POST",
    category: "edge-function",
    service: "supabase",
    description: "Web search for workspace intelligence gathering",
    auth: "service-role",
    status: "active",
  },

  // ── Contract Service (Fastify microservice) ──
  {
    path: "/health",
    method: "GET",
    category: "contract-service",
    service: "contract-service",
    description: "Contract service health check",
    auth: "public",
    status: "active",
  },
  {
    path: "/contracts",
    method: "GET",
    category: "contract-service",
    service: "contract-service",
    description: "List contracts with filters",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts",
    method: "POST",
    category: "contract-service",
    service: "contract-service",
    description: "Create a new contract instance",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts/:id",
    method: "GET",
    category: "contract-service",
    service: "contract-service",
    description: "Get contract by ID with events",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts/:id",
    method: "PATCH",
    category: "contract-service",
    service: "contract-service",
    description: "Update contract metadata",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts/:id/send",
    method: "POST",
    category: "contract-service",
    service: "contract-service",
    description: "Send contract for e-signing",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts/:id/cancel",
    method: "POST",
    category: "contract-service",
    service: "contract-service",
    description: "Cancel a pending contract",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts/:id/remind",
    method: "POST",
    category: "contract-service",
    service: "contract-service",
    description: "Send signing reminder",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/contracts/:id/events",
    method: "GET",
    category: "contract-service",
    service: "contract-service",
    description: "Get contract audit trail events",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/templates",
    method: "GET",
    category: "contract-service",
    service: "contract-service",
    description: "List contract templates",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/templates",
    method: "POST",
    category: "contract-service",
    service: "contract-service",
    description: "Create contract template",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/templates/:id",
    method: "GET",
    category: "contract-service",
    service: "contract-service",
    description: "Get template by ID",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/templates/:id",
    method: "PATCH",
    category: "contract-service",
    service: "contract-service",
    description: "Update contract template",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/templates/:id/render",
    method: "POST",
    category: "contract-service",
    service: "contract-service",
    description: "Render template with variables to HTML/PDF",
    auth: "api-key",
    status: "active",
  },

  // ── Public API (workspace-api Edge Function) ──
  {
    path: "/functions/v1/workspace-api/v1/profiles",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List employees in workspace",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/workspace-api/v1/departments",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List departments",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/workspace-api/v1/teams",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List teams",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/workspace-api/v1/locations",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List locations",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/workspace-api/v1/protocols",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List training protocols",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/workspace-api/v1/assignments",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List protocol assignments",
    auth: "api-key",
    status: "active",
  },
  {
    path: "/functions/v1/workspace-api/v1/contracts",
    method: "GET",
    category: "public-api",
    service: "workspace-api",
    description: "List employment contracts (metadata only)",
    auth: "api-key",
    status: "active",
  },
];

export const categoryLabels: Record<ApiEndpoint["category"], string> = {
  auth: "Auth",
  dashboard: "Dashboard",
  "platform-admin": "Platform Admin",
  webhook: "Webhook",
  system: "System",
  "contract-service": "Contract Service",
  "edge-function": "Edge Function",
  "public-api": "Public API",
};

export const serviceLabels: Record<ApiEndpoint["service"], string> = {
  web: "Next.js (web)",
  "contract-service": "Fastify (contract-service)",
  supabase: "Supabase Edge Functions",
  "workspace-api": "Workspace API (Edge Function)",
};
