/**
 * Event Config Registry — maps every notification event_key to its static config.
 * This is the single source of truth for how each notification type behaves:
 * priority, allowed channels, grouping window, i18n keys, and action URLs.
 */

export type NotificationEventConfig = {
  event_key: string;
  mode: "training" | "work" | "community";
  default_priority: 0 | 1 | 2;
  group_key_template: string | null;
  title_template: string;
  body_template: string;
  title_i18n_key: string;
  body_i18n_key: string;
  action_url_template: string;
  icon_type: string;
  allowed_channels: ("push" | "email" | "sms" | "in_app")[];
  grouping_window_sec: number;
  admin_overridable: boolean;
};

export const NOTIFICATION_EVENTS: Record<string, NotificationEventConfig> = {
  "shift.published": {
    event_key: "shift.published",
    mode: "work",
    default_priority: 1,
    group_key_template: "shift:{department_id}:{date}",
    title_template: "Ny vakt {date} kl {start_time}",
    body_template: "Du har fått en vakt i {department_name}",
    title_i18n_key: "notifications.shift.published.title",
    body_i18n_key: "notifications.shift.published.body",
    action_url_template: "/dashboard/my-schedule?date={date}",
    icon_type: "shift",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 180,
    admin_overridable: true,
  },
  "shift.updated": {
    event_key: "shift.updated",
    mode: "work",
    default_priority: 1,
    group_key_template: "shift:{department_id}:{date}",
    title_template: "Vaktendring {date}",
    body_template: "Vakten din i {department_name} er oppdatert",
    title_i18n_key: "notifications.shift.updated.title",
    body_i18n_key: "notifications.shift.updated.body",
    action_url_template: "/dashboard/my-schedule?date={date}",
    icon_type: "shift",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 180,
    admin_overridable: true,
  },
  "task.assigned": {
    event_key: "task.assigned",
    mode: "work",
    default_priority: 0,
    group_key_template: "task:{session_id}",
    title_template: "Ny oppgave tildelt",
    body_template: "Du har fått en ny oppgave",
    title_i18n_key: "notifications.task.assigned.title",
    body_i18n_key: "notifications.task.assigned.body",
    action_url_template: "/dashboard",
    icon_type: "task",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 180,
    admin_overridable: false,
  },
  "chat.message": {
    event_key: "chat.message",
    mode: "community",
    default_priority: 0,
    group_key_template: "chat:{channel_id}",
    title_template: "Ny melding i {channel_name}",
    body_template: "{sender_name}: {preview}",
    title_i18n_key: "notifications.chat.message.title",
    body_i18n_key: "notifications.chat.message.body",
    action_url_template: "/dashboard/komm/{channel_id}",
    icon_type: "chat",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 180,
    admin_overridable: false,
  },
  "deviation.reported": {
    event_key: "deviation.reported",
    mode: "work",
    default_priority: 2,
    group_key_template: null,
    title_template: "Avvik rapportert",
    body_template: "Et avvik er registrert i {department_name}",
    title_i18n_key: "notifications.deviation.reported.title",
    body_i18n_key: "notifications.deviation.reported.body",
    action_url_template: "/dashboard/operations",
    icon_type: "deviation",
    allowed_channels: ["push", "sms", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
  "join.request": {
    event_key: "join.request",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Ny søknad mottatt",
    body_template: "En ny person ønsker å bli med",
    title_i18n_key: "notifications.join.request.title",
    body_i18n_key: "notifications.join.request.body",
    action_url_template: "/dashboard/people",
    icon_type: "info",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "protocol.assigned": {
    event_key: "protocol.assigned",
    mode: "training",
    default_priority: 0,
    group_key_template: null,
    title_template: "Ny opplæring tildelt",
    body_template: "Du har fått tildelt et nytt opplæringsprotokoll",
    title_i18n_key: "notifications.protocol.assigned.title",
    body_i18n_key: "notifications.protocol.assigned.body",
    action_url_template: "/dashboard/my-training",
    icon_type: "training",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "approval.pending": {
    event_key: "approval.pending",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Godkjenning venter",
    body_template: "En godkjenning venter på deg",
    title_i18n_key: "notifications.approval.pending.title",
    body_i18n_key: "notifications.approval.pending.body",
    action_url_template: "/dashboard/reconciliation",
    icon_type: "approval",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
  "training.deadline": {
    event_key: "training.deadline",
    mode: "training",
    default_priority: 1,
    group_key_template: null,
    title_template: "Opplæringsfrist nærmer seg",
    body_template: "Fristen for {protocol_name} nærmer seg",
    title_i18n_key: "notifications.training.deadline.title",
    body_i18n_key: "notifications.training.deadline.body",
    action_url_template: "/dashboard/my-training",
    icon_type: "training",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
  "shift.punched_in": {
    event_key: "shift.punched_in",
    mode: "work",
    default_priority: 0,
    group_key_template: "punch:{department_id}:{date}",
    title_template: "Innstemplet",
    body_template: "{employee_name} har stemplet inn",
    title_i18n_key: "notifications.shift.punched_in.title",
    body_i18n_key: "notifications.shift.punched_in.body",
    action_url_template: "/dashboard/shift-clock",
    icon_type: "shift",
    allowed_channels: ["in_app"],
    grouping_window_sec: 300,
    admin_overridable: true,
  },
  "shift.punched_out": {
    event_key: "shift.punched_out",
    mode: "work",
    default_priority: 0,
    group_key_template: "punch:{department_id}:{date}",
    title_template: "Utstemplet",
    body_template: "{employee_name} har stemplet ut",
    title_i18n_key: "notifications.shift.punched_out.title",
    body_i18n_key: "notifications.shift.punched_out.body",
    action_url_template: "/dashboard/shift-clock",
    icon_type: "shift",
    allowed_channels: ["in_app"],
    grouping_window_sec: 300,
    admin_overridable: true,
  },
  "shift.late": {
    event_key: "shift.late",
    mode: "work",
    default_priority: 2,
    group_key_template: null,
    title_template: "Sen ankomst",
    body_template: "{employee_name} har ikke stemplet inn til vakt kl {start_time}",
    title_i18n_key: "notifications.shift.late.title",
    body_i18n_key: "notifications.shift.late.body",
    action_url_template: "/dashboard/shift-clock",
    icon_type: "deviation",
    allowed_channels: ["push", "in_app", "email"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "shift.no_show": {
    event_key: "shift.no_show",
    mode: "work",
    default_priority: 2,
    group_key_template: null,
    title_template: "Manglende oppmøte",
    body_template: "{employee_name} møtte ikke til vakt",
    title_i18n_key: "notifications.shift.no_show.title",
    body_i18n_key: "notifications.shift.no_show.body",
    action_url_template: "/dashboard/shift-clock",
    icon_type: "deviation",
    allowed_channels: ["push", "in_app", "email"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "shift.adhoc_pending": {
    event_key: "shift.adhoc_pending",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Tilleggsvakt venter",
    body_template: "En tilleggsvakt venter på godkjenning",
    title_i18n_key: "notifications.shift.adhoc_pending.title",
    body_i18n_key: "notifications.shift.adhoc_pending.body",
    action_url_template: "/dashboard/shift-clock",
    icon_type: "approval",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "session.hook": {
    event_key: "session.hook",
    mode: "work",
    default_priority: 0,
    group_key_template: "hook:{session_id}",
    title_template: "Oppgave utløst",
    body_template: "En planlagt oppgave er klar",
    title_i18n_key: "notifications.session.hook.title",
    body_i18n_key: "notifications.session.hook.body",
    action_url_template: "/dashboard/operations",
    icon_type: "task",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 180,
    admin_overridable: false,
  },
  "engine.reconciliation_feedback": {
    event_key: "engine.reconciliation_feedback",
    mode: "work",
    default_priority: 0,
    group_key_template: null,
    title_template: "Tilbakemelding på avstemming",
    body_template: "Avstemmingen for {date} har fått tilbakemelding",
    title_i18n_key: "notifications.engine.reconciliation_feedback.title",
    body_i18n_key: "notifications.engine.reconciliation_feedback.body",
    action_url_template: "/dashboard/reconciliation",
    icon_type: "approval",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "engine.day_closed": {
    event_key: "engine.day_closed",
    mode: "work",
    default_priority: 0,
    group_key_template: null,
    title_template: "Dagen er avsluttet",
    body_template: "Driften for {date} er lukket",
    title_i18n_key: "notifications.engine.day_closed.title",
    body_i18n_key: "notifications.engine.day_closed.body",
    action_url_template: "/dashboard/reconciliation",
    icon_type: "info",
    allowed_channels: ["in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "engine.workspace_ready": {
    event_key: "engine.workspace_ready",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Arbeidsområdet er klart",
    body_template: "Arbeidsområdet ditt er satt opp og klart til bruk",
    title_i18n_key: "notifications.engine.workspace_ready.title",
    body_i18n_key: "notifications.engine.workspace_ready.body",
    action_url_template: "/dashboard",
    icon_type: "info",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "engine.onboarding_welcome": {
    event_key: "engine.onboarding_welcome",
    mode: "training",
    default_priority: 0,
    group_key_template: null,
    title_template: "Velkommen!",
    body_template: "Velkommen til teamet! Start opplæringen din her",
    title_i18n_key: "notifications.engine.onboarding_welcome.title",
    body_i18n_key: "notifications.engine.onboarding_welcome.body",
    action_url_template: "/dashboard/my-training",
    icon_type: "training",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "engine.onboarding_complete": {
    event_key: "engine.onboarding_complete",
    mode: "training",
    default_priority: 1,
    group_key_template: null,
    title_template: "Opplæring fullført!",
    body_template: "Gratulerer — du har fullført all opplæring",
    title_i18n_key: "notifications.engine.onboarding_complete.title",
    body_i18n_key: "notifications.engine.onboarding_complete.body",
    action_url_template: "/dashboard",
    icon_type: "training",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "engine.session_hook_task": {
    event_key: "engine.session_hook_task",
    mode: "work",
    default_priority: 0,
    group_key_template: "hook:{session_id}",
    title_template: "Oppgave klar",
    body_template: "En planlagt oppgave er utløst for økten",
    title_i18n_key: "notifications.engine.session_hook_task.title",
    body_i18n_key: "notifications.engine.session_hook_task.body",
    action_url_template: "/dashboard/operations",
    icon_type: "task",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 180,
    admin_overridable: false,
  },
  "call.incoming": {
    event_key: "call.incoming",
    mode: "community",
    default_priority: 2,
    group_key_template: null,
    title_template: "Innkommende samtale fra {caller_name}",
    body_template: "",
    title_i18n_key: "notifications.call.incoming.title",
    body_i18n_key: "notifications.call.incoming.body",
    action_url_template: "/dashboard/komm/{channel_id}",
    icon_type: "chat",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "call.missed": {
    event_key: "call.missed",
    mode: "community",
    default_priority: 1,
    group_key_template: null,
    title_template: "Missat samtal fra {caller_name}",
    body_template: "",
    title_i18n_key: "notifications.call.missed.title",
    body_i18n_key: "notifications.call.missed.body",
    action_url_template: "/dashboard/komm/{channel_id}",
    icon_type: "chat",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },

  // ─── Shift Swap ──────────────────────────────────────────
  "shift.swap_initiated": {
    event_key: "shift.swap_initiated",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Byttforespørsel mottatt",
    body_template: "{requester_name} vil bytte vakt med deg ({date})",
    title_i18n_key: "notifications.shift.swap_initiated.title",
    body_i18n_key: "notifications.shift.swap_initiated.body",
    action_url_template: "/dashboard/schedule",
    icon_type: "shift",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "shift.swap_approved": {
    event_key: "shift.swap_approved",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Vaktbytte godkjent",
    body_template: "Vakten din {date} er byttet med {other_name}",
    title_i18n_key: "notifications.shift.swap_approved.title",
    body_i18n_key: "notifications.shift.swap_approved.body",
    action_url_template: "/dashboard/my-schedule",
    icon_type: "shift",
    allowed_channels: ["push", "email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "shift.swap_rejected": {
    event_key: "shift.swap_rejected",
    mode: "work",
    default_priority: 0,
    group_key_template: null,
    title_template: "Vaktbytte avslått",
    body_template: "Byttforespørselen din for {date} ble avslått",
    title_i18n_key: "notifications.shift.swap_rejected.title",
    body_i18n_key: "notifications.shift.swap_rejected.body",
    action_url_template: "/dashboard/schedule",
    icon_type: "shift",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "shift.swap_cancelled": {
    event_key: "shift.swap_cancelled",
    mode: "work",
    default_priority: 0,
    group_key_template: null,
    title_template: "Vaktbytte kansellert",
    body_template: "{requester_name} kansellerte byttforespørselen for {date}",
    title_i18n_key: "notifications.shift.swap_cancelled.title",
    body_i18n_key: "notifications.shift.swap_cancelled.body",
    action_url_template: "/dashboard/schedule",
    icon_type: "shift",
    allowed_channels: ["in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },

  // ─── Contract Lifecycle ──────────────────────────────────
  "contract.created": {
    event_key: "contract.created",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Ny kontrakt opprettet",
    body_template: "En ny kontrakt er opprettet for {employee_name}",
    title_i18n_key: "notifications.contract.created.title",
    body_i18n_key: "notifications.contract.created.body",
    action_url_template: "/dashboard/people/contracts",
    icon_type: "contract",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.sent": {
    event_key: "contract.sent",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Kontrakt klar for signering",
    body_template: "Du har en kontrakt som venter på signering",
    title_i18n_key: "notifications.contract.sent.title",
    body_i18n_key: "notifications.contract.sent.body",
    action_url_template: "/dashboard/people/contracts",
    icon_type: "contract",
    allowed_channels: ["email", "push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.viewed": {
    event_key: "contract.viewed",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Kontrakt åpnet",
    body_template: "{employee_name} har åpnet kontrakten",
    title_i18n_key: "notifications.contract.viewed.title",
    body_i18n_key: "notifications.contract.viewed.body",
    action_url_template: "/dashboard/people",
    icon_type: "contract",
    allowed_channels: ["in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.signed": {
    event_key: "contract.signed",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Kontrakt signert",
    body_template: "{employee_name} har signert kontrakten",
    title_i18n_key: "notifications.contract.signed.title",
    body_i18n_key: "notifications.contract.signed.body",
    action_url_template: "/dashboard/people/contracts",
    icon_type: "contract",
    allowed_channels: ["email", "push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.declined": {
    event_key: "contract.declined",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Kontrakt avslått",
    body_template: "{employee_name} har avslått kontrakten",
    title_i18n_key: "notifications.contract.declined.title",
    body_i18n_key: "notifications.contract.declined.body",
    action_url_template: "/dashboard/people",
    icon_type: "contract",
    allowed_channels: ["email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.expired": {
    event_key: "contract.expired",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Kontrakt utløpt",
    body_template: "Kontrakten for {employee_name} har utløpt",
    title_i18n_key: "notifications.contract.expired.title",
    body_i18n_key: "notifications.contract.expired.body",
    action_url_template: "/dashboard/people/contracts",
    icon_type: "contract",
    allowed_channels: ["email", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.intake_completed": {
    event_key: "contract.intake_completed",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Onboarding-data fullført",
    body_template: "{employee_name} har fullført alle påkrevde felt",
    title_i18n_key: "notifications.contract.intake_completed.title",
    body_i18n_key: "notifications.contract.intake_completed.body",
    action_url_template: "/dashboard/people",
    icon_type: "contract",
    allowed_channels: ["in_app", "push"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },
  "contract.reminder_due": {
    event_key: "contract.reminder_due",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Påminnelse: Signer kontrakt",
    body_template: "Du har en kontrakt som venter på signering",
    title_i18n_key: "notifications.contract.reminder_due.title",
    body_i18n_key: "notifications.contract.reminder_due.body",
    action_url_template: "/dashboard/people/contracts",
    icon_type: "contract",
    allowed_channels: ["email", "push"],
    grouping_window_sec: 0,
    admin_overridable: false,
  },

  // ─── Shift Reminders ─────────────────────────────────────
  "shift.confirmation_reminder": {
    event_key: "shift.confirmation_reminder",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Bekreft vakt",
    body_template: "Du har en ubekreftet vakt {date} kl {start_time}",
    title_i18n_key: "notifications.shift.confirmation_reminder.title",
    body_i18n_key: "notifications.shift.confirmation_reminder.body",
    action_url_template: "/dashboard/my-schedule",
    icon_type: "shift",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
  "shift.reminder_24h": {
    event_key: "shift.reminder_24h",
    mode: "work",
    default_priority: 0,
    group_key_template: null,
    title_template: "Vakt i morgen",
    body_template: "Du har vakt i morgen kl {start_time}",
    title_i18n_key: "notifications.shift.reminder_24h.title",
    body_i18n_key: "notifications.shift.reminder_24h.body",
    action_url_template: "/dashboard/my-schedule",
    icon_type: "shift",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
  "shift.reminder_4h": {
    event_key: "shift.reminder_4h",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Vakt om 4 timer",
    body_template: "Vakten din starter kl {start_time}",
    title_i18n_key: "notifications.shift.reminder_4h.title",
    body_i18n_key: "notifications.shift.reminder_4h.body",
    action_url_template: "/dashboard/my-schedule",
    icon_type: "shift",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
  "shift.reminder_2h": {
    event_key: "shift.reminder_2h",
    mode: "work",
    default_priority: 1,
    group_key_template: null,
    title_template: "Vakt om 2 timer",
    body_template: "Vakten din starter snart — kl {start_time}",
    title_i18n_key: "notifications.shift.reminder_2h.title",
    body_i18n_key: "notifications.shift.reminder_2h.body",
    action_url_template: "/dashboard/my-schedule",
    icon_type: "shift",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },

  // ─── Task Due Reminders ──────────────────────────────────
  "task.due_soon": {
    event_key: "task.due_soon",
    mode: "work",
    default_priority: 1,
    group_key_template: "task:{task_id}",
    title_template: "Oppgave forfaller snart",
    body_template: "{task_title} forfaller {due_label}",
    title_i18n_key: "notifications.task.due_soon.title",
    body_i18n_key: "notifications.task.due_soon.body",
    action_url_template: "/dashboard/operations",
    icon_type: "task",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 300,
    admin_overridable: true,
  },
  "task.overdue": {
    event_key: "task.overdue",
    mode: "work",
    default_priority: 2,
    group_key_template: "task:{task_id}",
    title_template: "Oppgave er forfalt",
    body_template: "{task_title} er forfalt",
    title_i18n_key: "notifications.task.overdue.title",
    body_i18n_key: "notifications.task.overdue.body",
    action_url_template: "/dashboard/operations",
    icon_type: "task",
    allowed_channels: ["push", "in_app"],
    grouping_window_sec: 0,
    admin_overridable: true,
  },
};

export function getEventConfig(eventKey: string): NotificationEventConfig | undefined {
  return NOTIFICATION_EVENTS[eventKey];
}

/** Interpolate {variable} placeholders with values from metadata */
export function interpolateTemplate(template: string, metadata: Record<string, unknown>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(metadata[key] ?? `{${key}}`));
}
