/**
 * InlineConfirmCard — HITL UI primitive for Botsson mutation confirmations.
 *
 * Pattern: Human-In-The-Loop confirm/edit/cancel flow rendered inline in the chat stream.
 * A sibling to the InputRequest (BIR) primitive; reuses the same roundtrip protocol
 * (ADR-0327) and session-channel enum from BIR.
 *
 * When a Botsson capability tool needs human confirmation before committing a mutation
 * (e.g. publish_announcement, send_message, approve_shift), the tool returns a
 * draft response containing a proposal_id. The LLM then calls `show_proposal_card`
 * with an InlineConfirmCardDescriptor, which the runtime forwards to the UI for
 * inline rendering with Bekreft / Endre / Avbryt affordances.
 *
 * Why this matters for Smartout:
 *   1. "Confident ≠ Authorized" — cascade C2 (render+decide) + C4 (gate-enforced commit).
 *      The card shows the draft; the gate enforces authorization at commit time.
 *   2. Stateless ID — proposal_id is the same UUID as the existing client_message_id
 *      generated by the capability tool. No new persistence, no engine_memory overload.
 *   3. Channel safety — voice can NEVER receive a card descriptor (ADR-0078).
 *      channel_constraint defaults to ["chat","voice"] but compose-verb tools set ["chat"].
 *   4. Mobile parity — schema lives in packages/ai/ from day one so mobile can render
 *      natively in Phase 2 (ADR-0133: web composes, mobile executes for approve_shift).
 *
 * Architecture B per ADR-0398: tool returns {phase:"draft"}, LLM calls show_proposal_card.
 * Symbol `ProposalCard` is BANNED — already used in ChangeProposalsPanel + ProposedPlanClient.
 * Discriminator field is `type`, NOT `kind`.
 *
 * References: ADR-0078 (channel pinning), ADR-0099 (gate levels), ADR-0133 (mobile boundary),
 * ADR-0151 (server-derived workspace_id), ADR-0327 (client-tool roundtrip), ADR-0398 (this
 * primitive), ADR-0399 (channel + platform descriptors).
 */

import { z } from "zod";
import { SessionChannelSchema } from "../input-request/types.js"; // reuse BIR's enum

// Re-export SessionChannelSchema so consumers of this module can import from one place.
export { SessionChannelSchema };
export type SessionChannel = z.infer<typeof SessionChannelSchema>;

// ── Surface enum ─────────────────────────────────────────────────────────────
// Identifies which mutation domain this card covers. Used by the UI for icon selection
// and accessibility labelling. Extensible — add new values via ADR amendment.
export const SurfaceSchema = z.enum(["announcement", "message", "shift_approve"]);
export type Surface = z.infer<typeof SurfaceSchema>;

// ── Platform enum (ADR-0399) ─────────────────────────────────────────────────
// Platform axis is orthogonal to channel axis. Two-field approach per ADR-0399 §Option 3.
export const PlatformSchema = z.enum(["web", "mobile"]);
export type Platform = z.infer<typeof PlatformSchema>;

// ── Action schemas ───────────────────────────────────────────────────────────
// Actions are a discriminated union on `id`. Exactly 2–3 actions required:
//   - confirm + cancel are MANDATORY
//   - edit is OPTIONAL (only when the tool exposes editable_fields)
// Tab order per ADR-0398 §Accessibility: Bekreft → Endre → Avbryt (happy-path-first).

export const ConfirmActionSchema = z.object({
  id: z.literal("confirm"),
  label: z.string().min(1).max(40),
  variant: z.literal("primary"),
});
export type ConfirmAction = z.infer<typeof ConfirmActionSchema>;

export const EditActionSchema = z.object({
  id: z.literal("edit"),
  label: z.string().min(1).max(40),
  variant: z.literal("ghost"),
  editable_fields: z.array(z.string()).min(1),
});
export type EditAction = z.infer<typeof EditActionSchema>;

export const CancelActionSchema = z.object({
  id: z.literal("cancel"),
  label: z.string().min(1).max(40),
  variant: z.literal("destructive"),
});
export type CancelAction = z.infer<typeof CancelActionSchema>;

export const ActionSchema = z.discriminatedUnion("id", [
  ConfirmActionSchema,
  EditActionSchema,
  CancelActionSchema,
]);
export type Action = z.infer<typeof ActionSchema>;

// ── Preview metadata ─────────────────────────────────────────────────────────
// Chips rendered under the body_excerpt. Up to 8 items.
// Visual contract from ADR-0398: bg-muted / text-muted-foreground font-mono text-[10px]
// tracking-widest uppercase. NEVER hardcoded colors.

export const PreviewMetadataItemSchema = z.object({
  label: z.string().min(1).max(30),
  value: z.string().min(1).max(80),
});
export type PreviewMetadataItem = z.infer<typeof PreviewMetadataItemSchema>;

export const PreviewSchema = z.object({
  title: z.string().min(1).max(120),
  body_excerpt: z.string().max(220).optional(), // ~200 chars + ellipsis (line-clamp-3)
  recipient_count: z.number().int().nonnegative().optional(),
  affected_entity: z.string().max(120).optional(),
  metadata: z.array(PreviewMetadataItemSchema).max(8).default([]),
});
export type Preview = z.infer<typeof PreviewSchema>;

// ── Primary descriptor ───────────────────────────────────────────────────────
// Returned inside show_proposal_card tool arguments. The discriminator field is `type`,
// NOT `kind` — mirrors BIR's type: z.literal("input_request") convention (ADR-0398 §Primitive).

export const InlineConfirmCardDescriptorSchema = z.object({
  type: z.literal("inline_confirm_card"), // DISCRIMINATOR — must be "inline_confirm_card"
  proposal_id: z.string().uuid(), // = client_message_id from capability tool
  surface: SurfaceSchema,
  draft: z.record(z.unknown()), // tool-specific draft payload (opaque to UI)
  preview: PreviewSchema,
  actions: z.array(ActionSchema).min(2).max(3), // confirm+cancel mandatory; edit optional
  voice_prompt: z.string().min(1).max(300).optional(), // server-controlled voice copy
  recipient_preview_available: z.boolean().optional(), // drives interactive vs static chip
  /**
   * Channel constraint per ADR-0399 §Option 3.
   * Defaults to ["chat","voice"] (unconstrained). Compose-verb tools set ["chat"].
   * Field name is channel_constraint (NOT allowed_channels — that name belongs to BIR).
   */
  channel_constraint: z.array(z.enum(["chat", "voice"])).default(["chat", "voice"]),
  /**
   * Platform constraint per ADR-0399 §Option 3.
   * Defaults to ["web","mobile"] (unconstrained). Compose-verb tools set ["web"].
   */
  platforms: z.array(PlatformSchema).default(["web", "mobile"]),
});
export type InlineConfirmCardDescriptor = z.infer<typeof InlineConfirmCardDescriptorSchema>;

// ── Result descriptor ────────────────────────────────────────────────────────
// POSTed back from browser → BFF → stage-engine as the ClientToolCallResult payload.
// Security note: `patch` is user-controlled and untrusted. Only whitelisted editable_fields
// from actions[id="edit"] are applied server-side. All gate-relevant params are re-derived
// server-side per ADR-0151 + L-0177 (silent-fallback ban).

export const InlineConfirmCardResultSchema = z.object({
  proposal_id: z.string().uuid(),
  action: z.enum(["confirm", "edit", "cancel"]),
  patch: z.record(z.unknown()).optional(), // only whitelisted editable_fields enforced server-side
});
export type InlineConfirmCardResult = z.infer<typeof InlineConfirmCardResultSchema>;

// ── Type guard ───────────────────────────────────────────────────────────────
/**
 * Returns true iff value is a valid InlineConfirmCardDescriptor.
 * The runtime calls this on every show_proposal_card tool argument to decide whether
 * to render an InlineConfirmCard or fall back to a text response.
 *
 * Uses full Zod parse (not a fast-path object check like BIR's isInputRequest) because
 * descriptor validity includes UUID format, action count, and enum membership — fast-path
 * would require duplicating all those checks and is therefore error-prone.
 */
export function isInlineConfirmCard(value: unknown): value is InlineConfirmCardDescriptor {
  return InlineConfirmCardDescriptorSchema.safeParse(value).success;
}

// ── Builder ──────────────────────────────────────────────────────────────────
/**
 * Builds an InlineConfirmCardDescriptor with sensible defaults applied via Zod parse.
 * Capability tools should use this rather than constructing the object manually — it
 * ensures defaults (channel_constraint, platforms, metadata) are applied and the
 * schema is validated at build time (throws on invalid input, not at render time).
 *
 * Usage in a capability tool (publish_announcement pattern):
 *   const descriptor = buildInlineConfirmCard({
 *     proposal_id: clientMessageId,
 *     surface: "announcement",
 *     draft: { title, body },
 *     preview: { title: "Publiser kunngjøring", body_excerpt: body.slice(0, 200), ... },
 *     actions: [
 *       { id: "confirm", label: "Bekreft", variant: "primary" },
 *       { id: "cancel", label: "Avbryt", variant: "destructive" },
 *     ],
 *     channel_constraint: ["chat"],  // compose-verb: chat-only per ADR-0399
 *     platforms: ["web"],            // compose-verb: web-only per ADR-0399
 *   });
 */
// Input type for the builder — uses z.input<> so callers can omit defaulted fields
// (channel_constraint, platforms, preview.metadata) without TypeScript errors.
export type InlineConfirmCardInput = z.input<typeof InlineConfirmCardDescriptorSchema>;

export function buildInlineConfirmCard(
  input: Omit<InlineConfirmCardInput, "type"> & { type?: "inline_confirm_card" },
): InlineConfirmCardDescriptor {
  const candidate = { type: "inline_confirm_card" as const, ...input };
  const parsed = InlineConfirmCardDescriptorSchema.parse(candidate);
  return parsed;
}
