#!/usr/bin/env bash
# seed-dev-day-tasks.sh
#
# Idempotently seeds demo session_task rows for the current local Supabase DB
# so the /dashboard/oppgaver Manager Timeline has something to render.
#
# Why: supabase/seed.sql ships zero session_task rows, so newly-reset dev DBs
# show an empty day on the oppgaver page. Real prod tasks are generated by
# session-template propagation + cron + agent flows — none of which fire in
# local dev without manual setup. This script fills the gap for demo/testing.
#
# Scope: targets HQ Workspace (b0000000-…) AND Villa Mat (b1000000-…), the
# two seed workspaces. Seeds tasks for today, today+1, today+2.
#
# Idempotency: skips rows that already exist (same workspace_id +
# department_session_id + title). Safe to re-run.
#
# Usage:
#   bash scripts/seed-dev-day-tasks.sh                    # default: 2 workspaces, today+next-2
#   WORKSPACE_ID=<uuid> bash scripts/seed-dev-day-tasks.sh   # target one workspace
#   DAYS_AHEAD=5       bash scripts/seed-dev-day-tasks.sh   # seed today + next 5 days
#
# Requires: Docker stack `supabase_db_smartout.ai` running.

set -euo pipefail

DB_CONTAINER="${DB_CONTAINER:-supabase_db_smartout.ai}"
DAYS_AHEAD="${DAYS_AHEAD:-2}"

WORKSPACE_FILTER=""
if [ -n "${WORKSPACE_ID:-}" ]; then
  WORKSPACE_FILTER="AND ds.workspace_id = '${WORKSPACE_ID}'::uuid"
fi

if ! docker ps --format '{{.Names}}' | grep -q "^${DB_CONTAINER}$"; then
  echo "ERROR: ${DB_CONTAINER} is not running. Run 'op run --env-file=.env.template -- npx supabase start' first." >&2
  exit 1
fi

# Department-specific task templates. Hour offset is in 24h; HH is the
# scheduled clock time. Three tasks per department per day = 12 tasks per
# workspace per day. Titles intentionally diverse so the timeline isn't
# visually uniform.
docker exec -i "${DB_CONTAINER}" psql -U postgres -d postgres <<SQL
BEGIN;

WITH template(department_name, title, hh, mm) AS (
  VALUES
    ('Kitchen',    'Mise en place — frokost',          9,  0),
    ('Kitchen',    'Sjekk kjølerom temp',              11, 30),
    ('Kitchen',    'Forberedelse middag',              15, 0),
    ('Bar',        'Restock bar — øl/vin',             10, 0),
    ('Bar',        'Telle kontanter midt-skift',       16, 0),
    ('Bar',        'Closing — vask espressomaskin',    22, 30),
    ('Service',    'Briefing — dagens meny',           10, 30),
    ('Service',    'Sjekk bordoppdekking',             12, 0),
    ('Service',    'Lunch debrief',                    15, 0),
    ('Operations', 'HMS-runde',                        9,  30),
    ('Operations', 'Sjekk varemottak',                 13, 0),
    ('Operations', 'Closing — kassesjekk',             23, 0)
)
INSERT INTO public.session_task (
  workspace_id,
  department_session_id,
  title,
  status,
  origin,
  generated_by,
  scheduled_at,
  created_at,
  updated_at
)
SELECT
  ds.workspace_id,
  ds.department_session_id,
  template.title,
  'pending'::session_task_status,
  'session'::task_origin,
  'system'::task_generated_by,
  ((ds.session_date::timestamp
    + (template.hh || ' hours')::interval
    + (template.mm || ' minutes')::interval) AT TIME ZONE 'Europe/Oslo') AS scheduled_at,
  now(),
  now()
FROM public.department_session ds
JOIN public.department d ON d.department_id = ds.department_id
JOIN template ON template.department_name = d.name
WHERE ds.session_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '${DAYS_AHEAD} days'
  ${WORKSPACE_FILTER}
  AND NOT EXISTS (
    SELECT 1 FROM public.session_task existing
    WHERE existing.workspace_id = ds.workspace_id
      AND existing.department_session_id = ds.department_session_id
      AND existing.title = template.title
  );

\\echo ''
\\echo 'Seeded session_task rows per workspace × date:'
SELECT
  ds.workspace_id::text AS workspace,
  ds.session_date,
  COUNT(*) AS tasks
FROM public.session_task st
JOIN public.department_session ds ON ds.department_session_id = st.department_session_id
WHERE ds.session_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '${DAYS_AHEAD} days'
  ${WORKSPACE_FILTER}
GROUP BY ds.workspace_id, ds.session_date
ORDER BY ds.workspace_id, ds.session_date;

COMMIT;
SQL

echo ""
echo "Done. Refresh /dashboard/oppgaver to see tasks."
