-- ADR-0187 implementation — single-emitter invariant for session state transitions
-- Council 2 verdict 2026-04-22
-- Part 1: Remove emit_event from department_session_lifecycle step 6
-- Part 2: Gate trg_session_pending_signoff via gate_action
-- Part 3: Seed session.auto_signoff_transition capability (min_role=system)

-- ============================================================
-- 20260516110000_consolidate_session_signoff_emitter.sql
--
-- Closes the triple-writer pattern (L-0108, 3rd occurrence) on
-- department_session.status='pending_signoff'. Before this migration
-- four writers could drive the transition with three divergent emit
-- paths:
--
--   1. trg_session_pending_signoff (canonical, kept + gated here)
--   2. engine_process department_session_lifecycle step 6 (deleted)
--   3. signoff-session-action.ts inline emit (stripped in app code)
--   4. session-lifecycle cron inline engine_event insert (stripped in app code)
--
-- Per ADR-0187: the trigger is the SOLE emit source. Application
-- writers change status; the trigger emits. Per ADR-0189 / ADR-0099:
-- DB-level writers must pass through the same authority gate as
-- application writers. This migration wires gate_action into the
-- trigger and seeds the matching capability.
--
-- Idempotence:
--   * CREATE OR REPLACE FUNCTION — safe to re-apply.
--   * engine_step DELETE for step 6 — idempotent; running instances
--     keep their engine_state_step rows (snapshotted at state create
--     per engine-dispatch getStepsForState), so deletion does not
--     orphan live runtime rows. Only new runs are affected.
--   * CHECK-constraint relax and capability seed are both guarded
--     with IF NOT EXISTS / ON CONFLICT DO NOTHING.
-- ============================================================

SET search_path TO public, extensions;

-- ──────────────────────────────────────────────
-- Part 1: Remove duplicate emit_event from
-- department_session_lifecycle step 6.
--
-- Safe wrt in-flight runs: engine-dispatch reads steps from
-- engine_state_step (runtime, already-populated) in preference to
-- engine_step (definition). Deleting the definition row removes only
-- the path for NEW runs; existing engine_state rows continue through
-- their snapshotted step list unchanged.
-- ──────────────────────────────────────────────

DELETE FROM public.engine_step
 WHERE process_id = 'department_session_lifecycle'
   AND step_order = 6;

COMMENT ON TABLE public.engine_step IS
  'Steps within a process. step_group enables parallel execution. '
  'Note: department_session_lifecycle step 6 was removed 2026-04-22 '
  'per ADR-0187 — trg_session_pending_signoff is now the sole emitter '
  'for department_session.pending_signoff.';

-- ──────────────────────────────────────────────
-- Part 2a: Relax engine_authority_config.min_role CHECK to include
-- 'system'. _role_rank already handles 'system' (rank 4); only the
-- CHECK constraint was missing the value. Required for the
-- system-floor capability seeded below.
-- ──────────────────────────────────────────────

DO $$
BEGIN
  -- Drop the existing CHECK (its name is autogenerated — locate by
  -- referencing the min_role column).
  IF EXISTS (
    SELECT 1
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
     WHERE t.relname = 'engine_authority_config'
       AND c.contype = 'c'
       AND pg_get_constraintdef(c.oid) ILIKE '%min_role%'
  ) THEN
    EXECUTE (
      SELECT 'ALTER TABLE public.engine_authority_config DROP CONSTRAINT ' || quote_ident(c.conname)
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
       WHERE t.relname = 'engine_authority_config'
         AND c.contype = 'c'
         AND pg_get_constraintdef(c.oid) ILIKE '%min_role%'
       LIMIT 1
    );
  END IF;

  ALTER TABLE public.engine_authority_config
    ADD CONSTRAINT engine_authority_config_min_role_check
    CHECK (min_role IN ('employee', 'manager', 'admin', 'owner', 'system'));
END $$;

COMMENT ON COLUMN public.engine_authority_config.min_role IS
  'Minimum profile role required to use this capability at the configured '
  'authority level. Profiles with lower roles get downgraded to suggest '
  'level regardless of workspace config. Value ''system'' added 2026-04-22 '
  '(ADR-0187) for DB-trigger / cron / engine_process system-initiated '
  'transitions where no human actor exists.';

-- ──────────────────────────────────────────────
-- Part 2b: Replace emit_session_pending_signoff_event() to gate via
-- gate_action BEFORE inserting engine_event. On deny → RAISE EXCEPTION
-- (aborts the UPDATE, keeps status integrity).
--
-- Rules:
--   * Workspace: NEW.workspace_id (non-null, column invariant).
--   * Actor: NULL (trigger has no user context — system callers
--           omit actor, gate_action handles null-safe path).
--   * Channel: 'system' (ADR-0078 — D6 state transitions not voice).
--   * Capability: 'session.auto_signoff_transition' (seeded below).
--   * entity_id: NEW.department_session_id for ADR-0101 scoping.
--
-- Default-allow remains in effect until the seed below lands for
-- the workspace (ADR-0099 §5). With seed present, min_role=system
-- means only the trigger path (no caller role) can pass.
-- ──────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.emit_session_pending_signoff_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_gate_result JSONB;
  v_gate_allow  BOOLEAN;
  v_gate_reason TEXT;
BEGIN
  IF NEW.status = 'pending_signoff' AND OLD.status = 'active' THEN
    -- ADR-0187 + ADR-0189: gate the trigger. DB-level writers must
    -- pass through the same authority gate as application writers.
    v_gate_result := public.gate_action(
      p_workspace_id      => NEW.workspace_id,
      p_capability        => 'session.auto_signoff_transition',
      p_channel           => 'system',
      p_actor_profile_id  => NULL,
      p_action_type       => 'pending_signoff',
      p_engine_process_id => NULL,
      p_engine_state_id   => NULL,
      p_approvers_present => ARRAY[]::UUID[],
      p_entity_id         => NEW.department_session_id
    );

    v_gate_allow  := COALESCE((v_gate_result->>'allow')::BOOLEAN, false);
    v_gate_reason := v_gate_result->>'reason';

    IF NOT v_gate_allow THEN
      RAISE EXCEPTION
        'session.auto_signoff_transition denied by gate_action: %',
        COALESCE(v_gate_reason, 'forbidden');
    END IF;

    INSERT INTO engine_event (
      event_type,
      workspace_id,
      payload,
      idempotency_key
    ) VALUES (
      'department_session.pending_signoff',
      NEW.workspace_id,
      jsonb_build_object(
        'department_session_id', NEW.department_session_id,
        'department_id', NEW.department_id,
        'session_date', NEW.session_date
      ),
      'session_signoff_' || NEW.department_session_id
    );
  END IF;
  RETURN NEW;
END;
$$;

-- Trigger definition unchanged — DROP/CREATE preserves idempotence.
DROP TRIGGER IF EXISTS trg_session_pending_signoff ON public.department_session;
CREATE TRIGGER trg_session_pending_signoff
  AFTER UPDATE OF status ON public.department_session
  FOR EACH ROW
  EXECUTE FUNCTION public.emit_session_pending_signoff_event();

COMMENT ON FUNCTION public.emit_session_pending_signoff_event() IS
  'ADR-0187: sole emitter for department_session active → pending_signoff '
  'transitions. Gates via gate_action(session.auto_signoff_transition, '
  'channel=system) per ADR-0189 before writing engine_event. Raises on '
  'denial to abort the UPDATE and preserve status integrity.';

-- ──────────────────────────────────────────────
-- Part 3: Seed session.auto_signoff_transition capability.
--
-- min_role='system' — only the trigger path (NULL actor) and
-- genuine system actors (Botsson profiles with role='system') can
-- pass. Human actors (employee / manager / admin / owner) are all
-- below the system floor and would be downgraded to 'suggest' →
-- treated as denied by the Server Action context (but they don't
-- call this capability; only the trigger does).
--
-- level='confirm' — matches existing session.* capability pattern;
-- no autonomous-agent surface for this capability.
-- ──────────────────────────────────────────────

DO $$
DECLARE
  v_updated_by uuid;
BEGIN
  SELECT user_id INTO v_updated_by
  FROM public.user_identity
  WHERE is_godmode = true
  ORDER BY created_at ASC
  LIMIT 1;

  IF v_updated_by IS NULL THEN
    RAISE NOTICE 'No godmode user found — skipping session.auto_signoff_transition authority seed. Re-run after first admin is created.';
    RETURN;
  END IF;

  INSERT INTO public.engine_authority_config (
    workspace_id, capability, level, min_role,
    requires_four_eyes, observer_escalation_hours, updated_by
  )
  SELECT w.workspace_id,
         'session.auto_signoff_transition',
         'confirm',
         'system',
         false,
         24,
         v_updated_by
    FROM public.workspace w
  ON CONFLICT (workspace_id, capability) DO NOTHING;
END $$;

COMMENT ON COLUMN public.engine_authority_config.capability IS
  'Capability name (matches packages/ai/src/capabilities/types.ts CapabilityName union). Added billing_query 2026-04-17; added session.signoff/session.close/broadcast.send 2026-05-15; added session.open/session.transition/shift.manual_time_entry 2026-04-20; added reconciliation.override/submit/wizard_submit_with_blocker/wizard_save 2026-04-22 (ADR-0189); added session.auto_signoff_transition 2026-04-22 (ADR-0187, min_role=system, gate-action caller = trg_session_pending_signoff).';
