-- Guardian Signal table
-- Foundation table for workspace health monitoring system.
-- Signals are generated by the guardian-sweep Edge Function and
-- displayed in the Guardian dashboard panel.

CREATE TABLE guardian_signal (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id    UUID NOT NULL REFERENCES workspace(workspace_id),
  signal_type     TEXT NOT NULL,
  domain          TEXT NOT NULL,          -- 'readiness' | 'workspace_maturity' | 'agent_behavior'
  severity        TEXT NOT NULL,          -- 'info' | 'warning' | 'critical'
  entity_type     TEXT,
  entity_id       UUID,
  entity_label    TEXT,
  title           TEXT NOT NULL,
  description     TEXT,
  data            JSONB DEFAULT '{}',
  status          TEXT NOT NULL DEFAULT 'active',  -- 'active' | 'acknowledged' | 'resolved' | 'dismissed'
  acknowledged_by UUID REFERENCES profile(profile_id),
  acknowledged_at TIMESTAMPTZ,
  resolved_at     TIMESTAMPTZ,
  source_check_id TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ
);

-- Active signals per workspace (primary query)
CREATE INDEX idx_guardian_signal_active
  ON guardian_signal (workspace_id, status, severity, created_at DESC)
  WHERE status = 'active';

-- Entity lookup
CREATE INDEX idx_guardian_signal_entity
  ON guardian_signal (workspace_id, entity_type, entity_id);

-- RLS
ALTER TABLE guardian_signal ENABLE ROW LEVEL SECURITY;

-- Managers/admins can view signals in their workspace
CREATE POLICY "Workspace members can view signals" ON guardian_signal
  FOR SELECT
  USING (workspace_id IN (SELECT get_workspace_ids_for_user(auth.uid())));

-- Service role inserts (guardian-sweep Edge Function)
CREATE POLICY "Service can manage signals" ON guardian_signal
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Seed engine_authority_config for guardian capability in all active workspaces.
-- Uses the workspace owner (first admin/owner profile) as updated_by.
INSERT INTO engine_authority_config (workspace_id, capability, level, updated_by)
SELECT DISTINCT ON (w.workspace_id) w.workspace_id, 'guardian', 'suggest', p.user_id
FROM workspace w
JOIN profile p ON p.workspace_id = w.workspace_id AND p.role IN ('owner', 'admin') AND p.is_active = true
WHERE w.is_active = true
ORDER BY w.workspace_id, (p.role = 'owner') DESC
ON CONFLICT (workspace_id, capability) DO NOTHING;
