-- Leader Pulse: Proactive engagement questions for workspace leaders
-- Generated by the leader-pulse Edge Function (cron, every 3 days).
-- Leaders see pending questions on their dashboard and can answer or dismiss.

CREATE TABLE leader_pulse (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id    UUID NOT NULL REFERENCES workspace(workspace_id) ON DELETE CASCADE,
  profile_id      UUID NOT NULL REFERENCES profile(profile_id) ON DELETE CASCADE,
  question        TEXT NOT NULL,
  context         JSONB DEFAULT '{}',
  status          TEXT NOT NULL DEFAULT 'pending',   -- pending | delivered | answered | expired
  delivered_via   TEXT,                               -- 'dashboard' | 'sms' | 'email'
  delivered_at    TIMESTAMPTZ,
  answered_at     TIMESTAMPTZ,
  answer          TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLS
ALTER TABLE leader_pulse ENABLE ROW LEVEL SECURITY;

-- JWT policy: leaders can see their own pulse questions
CREATE POLICY "users_read_own_pulse" ON leader_pulse
  FOR SELECT USING (
    profile_id IN (
      SELECT profile_id FROM profile WHERE user_id = auth.uid()
    )
  );

-- JWT policy: leaders can update (answer) their own
CREATE POLICY "users_update_own_pulse" ON leader_pulse
  FOR UPDATE USING (
    profile_id IN (
      SELECT profile_id FROM profile WHERE user_id = auth.uid()
    )
  );

-- Service role has full access (for cron function — bypasses RLS automatically)

-- Indexes
CREATE INDEX idx_leader_pulse_status ON leader_pulse(status) WHERE status = 'pending';
CREATE INDEX idx_leader_pulse_workspace ON leader_pulse(workspace_id);
CREATE INDEX idx_leader_pulse_profile ON leader_pulse(profile_id, status);

-- updated_at trigger (reuse existing public.set_updated_at() function)
CREATE TRIGGER set_leader_pulse_updated_at
  BEFORE UPDATE ON leader_pulse
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
