-- Settlement artifacts bucket — declarative provisioning + RLS + mime_type column.
-- Replaces lazy ensureBucketExists() in packages/billing/src/server/settlement/run.ts.
-- Per V4 audit (2026-05-02): bucket must reproduce from supabase db reset.

-- ── Bucket ───────────────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'settlement-artifacts',
  'settlement-artifacts',
  false,                              -- private; downloads via signed URL only
  52428800,                           -- 50 MB per artifact (matches old runtime call)
  ARRAY['application/pdf', 'text/csv']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ── Storage RLS — service-role write only, no anon ───────────────────────
CREATE POLICY "settlement_artifacts_service_role_write"
  ON storage.objects
  FOR ALL
  TO service_role
  USING (bucket_id = 'settlement-artifacts')
  WITH CHECK (bucket_id = 'settlement-artifacts');

CREATE POLICY "settlement_artifacts_no_anon_read"
  ON storage.objects
  FOR SELECT
  TO anon
  USING (false);

-- Authenticated users CANNOT read directly — downloads go via signed URL
-- generated by service-role in apps/admin/src/app/api/avstemming/[run_id]/artifact/[type]/route.ts
-- per ADR-0262.

-- ── settlement_artifact mime_type column ─────────────────────────────────
ALTER TABLE billing.settlement_artifact
  ADD COLUMN IF NOT EXISTS mime_type text;

-- Backfill from artifact_type for existing rows.
UPDATE billing.settlement_artifact
SET mime_type = CASE artifact_type::text
  WHEN 'detail_csv' THEN 'text/csv'
  WHEN 'summary_pdf' THEN 'application/pdf'
  WHEN 'invoice_bundle_pdf' THEN 'application/pdf'
  WHEN 'discrepancy_pdf' THEN 'application/pdf'
  ELSE 'application/octet-stream'
END
WHERE mime_type IS NULL;

ALTER TABLE billing.settlement_artifact
  ALTER COLUMN mime_type SET NOT NULL;

COMMENT ON COLUMN billing.settlement_artifact.mime_type IS
  'IANA media type stored alongside Storage object metadata. Set on INSERT by run.ts.';
